# Generated by Django 4.1.7 on 2023-05-11 04:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_alter_groupquestion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
