# Generated by Django 4.1.7 on 2023-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLPT', '0003_alter_profile_id_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
