# Generated by Django 4.1.7 on 2023-05-11 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_alter_exam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
