# Generated by Django 4.1.7 on 2023-05-11 03:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_alter_groupquestion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
