# Generated by Django 4.2 on 2023-05-12 02:32

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_alter_groupquestion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='D:\\PBL5_Final\\PBL5_Final\\media'), upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
