# Generated by Django 4.2 on 2023-06-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_alter_exam_image_alter_question_content'),
        ('Exam', '0009_remove_groupquestion_audio'),
    ]

    operations = [
    ]
