# Generated by Django 4.1.7 on 2023-06-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0011_alter_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampart',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exampart',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exam.exam'),
        ),
    ]
