# Generated by Django 4.1.7 on 2023-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0012_exampart_category_alter_exampart_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampart',
            name='category',
            field=models.CharField(blank=True, choices=[('Listening', 'Listening'), ('Reading', 'Reading'), ('Grammar', 'Grammar'), ('Vocabulary', 'Vocabulary')], max_length=100, null=True),
        ),
    ]
