# Generated by Django 4.2.1 on 2023-06-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0012_alter_exam_image'),
        ('Exam', '0013_alter_exampart_category'),
    ]

    operations = [
    ]
