# Generated by Django 4.1.7 on 2023-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0013_alter_exampart_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exampart',
            old_name='category',
            new_name='skill',
        ),
        migrations.AddField(
            model_name='exampart',
            name='level',
            field=models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], max_length=100, null=True),
        ),
    ]
