# Generated by Django 4.2 on 2023-06-05 16:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0013_alter_exampart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='D:\\PBL5_Final\\PBL5_Final\\media'), upload_to='media/'),
        ),
    ]
