# Generated by Django 4.2.1 on 2023-06-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0014_merge_20230604_0940'),
        ('Exam', '0014_rename_category_exampart_skill_exampart_level'),
    ]

    operations = [
    ]
