# Generated by Django 4.2.1 on 2023-06-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0015_exampart_user'),
        ('Exam', '0015_merge_20230607_0731'),
    ]

    operations = [
    ]
