# Generated by Django 4.2 on 2023-06-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0014_alter_exam_image'),
        ('Exam', '0015_exampart_user'),
    ]

    operations = [
    ]
