# Generated by Django 4.2.2 on 2023-06-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0015_exampart_user'),
        ('Exam', '0016_alter_exam_image'),
    ]

    operations = [
    ]
