# Generated by Django 4.2.1 on 2023-06-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0016_merge_0014_alter_exam_image_0015_exampart_user'),
        ('Exam', '0016_merge_0015_exampart_user_0015_merge_20230607_0731'),
    ]

    operations = [
    ]
