# Generated by Django 4.1.7 on 2023-06-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0016_alter_exam_image'),
        ('Exam', '0016_merge_0015_exampart_user_0015_merge_20230607_0731'),
    ]

    operations = [
    ]
