# Generated by Django 4.1.7 on 2023-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0017_alter_exam_image'),
        ('Exam', '0017_merge_20230608_0829'),
    ]

    operations = [
    ]
