# Generated by Django 4.2.1 on 2023-06-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0018_alter_exam_image'),
        ('Exam', '0018_merge_0017_alter_exam_image_0017_merge_20230608_0829'),
    ]

    operations = [
    ]
