# Generated by Django 4.2 on 2023-06-10 12:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0019_merge_20230609_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='D:\\PBL5_Final\\PBL5_Final\\media'), upload_to='media/'),
        ),
    ]
