# Generated by Django 4.1.7 on 2023-05-14 07:55

import ckeditor.fields
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exam', '0006_alter_question_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/history')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='/home/holequoctin/Documents/Nam3_Ki2/PBL5/PBL5/PBL5_Final/PBL5_Final/media'), upload_to='media/history')),
                ('pass_score', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('correct', models.CharField(default='A', max_length=1)),
                ('group_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.groupquestionhistory')),
            ],
        ),
        migrations.CreateModel(
            name='PracticePartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('pass_score', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('time_left', models.DurationField()),
                ('practice_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.practicehistory')),
            ],
        ),
        migrations.AddField(
            model_name='groupquestionhistory',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.practiceparthistory'),
        ),
    ]
