# Generated by Django 4.1.7 on 2023-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_questionhistory_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicehistory',
            name='scored',
            field=models.IntegerField(default=0),
        ),
    ]
