# Generated by Django 4.1.7 on 2023-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_practicehistory_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicehistory',
            name='base_score',
            field=models.IntegerField(default=0),
        ),
    ]
