# Generated by Django 4.2.1 on 2023-06-03 09:02
# Generated by Django 4.2 on 2023-06-05 16:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_practicehistory_base_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicehistory',
            name='image',
            # field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='E:\\ki_6\\PBL\\PBL5_Final\\PBL5_Final\\media'), upload_to='media/history'),
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='D:\\PBL5_Final\\PBL5_Final\\media'), upload_to='media/history'),
        ),
    ]
