# Generated by Django 4.1.7 on 2023-06-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_practicehistory_base_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceparthistory',
            name='practice_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.practicehistory'),
        ),
    ]
