# Generated by Django 4.1.7 on 2023-06-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0014_rename_category_exampart_skill_exampart_level'),
        ('Student', '0008_alter_practiceparthistory_practice_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceparthistory',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exam.exampart'),
        ),
    ]
