# Generated by Django 4.1.7 on 2023-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_practiceparthistory_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceparthistory',
            name='scored',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
