# Generated by Django 4.2.1 on 2023-06-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_practicehistory_image'),
        ('Student', '0010_practiceparthistory_scored'),
    ]

    operations = [
    ]
