# Generated by Django 4.1.7 on 2023-06-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0011_practiceparthistory_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceparthistory',
            name='practice_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PracticeHistory', to='Student.practicehistory'),
        ),
        migrations.AlterField(
            model_name='practiceparthistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentSkill', to=settings.AUTH_USER_MODEL),
        ),
    ]
