# Generated by Django 4.2.2 on 2023-06-07 15:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_merge_20230607_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicehistory',
            name='image',
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='/home/holequoctin/Documents/Nam3_Ki2/PBL5/PBL5/PBL5_Final/PBL5_Final/media'), upload_to='media/history'),
        ),
    ]
