# Generated by Django 4.1.7 on 2023-06-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_alter_practiceparthistory_practice_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceparthistory',
            name='base_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
