# Generated by Django 4.1.7 on 2023-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_practiceparthistory_base_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceparthistory',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
