# Generated by Django 4.2.1 on 2023-06-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_merge_20230607_0731'),
        ('Student', '0016_remove_practiceparthistory_user'),
    ]

    operations = [
    ]
