# Generated by Django 4.2.2 on 2023-06-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_alter_practicehistory_image'),
        ('Student', '0016_remove_practiceparthistory_user'),
    ]

    operations = [
    ]
