# Generated by Django 4.1.7 on 2023-06-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_alter_practicehistory_image'),
        ('Student', '0017_merge_20230607_2249'),
    ]

    operations = [
    ]
