# Generated by Django 4.2.1 on 2023-06-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_merge_20230607_2249'),
        ('Student', '0017_merge_20230608_1011'),
    ]

    operations = [
    ]
