# Generated by Django 4.1.7 on 2023-06-08 08:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_merge_20230608_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicehistory',
            name='image',
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='/home/holequoctin/Documents/Nam3_Ki2/PBL5/PBL5/PBL5_Final/PBL5_Final/media'), upload_to='media/history'),
        ),
    ]
