# Generated by Django 4.1.7 on 2023-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_alter_practicehistory_image'),
        ('Student', '0018_merge_20230608_0829'),
    ]

    operations = [
    ]
