# Generated by Django 4.2.1 on 2023-06-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_merge_20230608_1413'),
        ('Student', '0019_merge_20230608_0845'),
    ]

    operations = [
    ]
