# Generated by Django 4.2.1 on 2023-06-10 04:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_merge_20230609_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicehistory',
            name='image',
            field=models.ImageField(default='media/jlpt.jpeg', storage=django.core.files.storage.FileSystemStorage(location='E:\\ki_6\\PBL\\PBL5_Final\\PBL5_Final\\media'), upload_to='media/history'),
        ),
    ]
