# Generated by Django 4.1.7 on 2023-05-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_practicehistory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='answer',
            field=models.CharField(blank=True, default='A', max_length=1, null=True),
        ),
    ]
