# Generated by Django 2.2 on 2023-04-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLPT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
